### PR TITLE
Add 404 page

### LINKED ISSUE #221: Set up 404 page

### PR DESCRIPTION
**Pull request by froggleston**
Fixes #221

### CODE REVIEW

**Comment by froggleston** [comment]
Still not working with the extension as it automatically injects prefixes to URLs e.g. `/en/latest`, and you cannot fully turn these off, i.e. setting the prefix configuration to `None` or `""` still adds a leading `/` character which breaks things.

**Comment by maneesha** [comment]
@froggleston It is set up on our current sphinx site.  I'm just not sure how.

**Comment by froggleston** [comment]
@maneesha The previous site uses a much older version of the extension that supports no prefix. However, unhelpfully, the extension devs removed this in later versions instead opting for "/" or a full prefix. There is no longer an option for no prefix. I can try the old version and see how it works.

**Comment by froggleston** [comment]
Strangely this seems to work now with the original extension.

**Comment by maneesha** [comment]
Thanks @froggleston 
Merging this but keeping the issue open because we should make the page text more useful.

**Pull request merged**
