### PR TITLE
Add content for CarpentryCon Handbook

### PR DESCRIPTION
**Pull request by acrall**
Added content from the [Virtual CarpentryCon Handbook](https://docs.google.com/document/d/1_3VJmbg1UDqinPYwCD1C55zXQXMvkhzw_lbc10U__CY/edit#) to .md file

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @acrall ! 
Can you try updating the headers based on the [instructions here](https://github.com/carpentries/handbook-beta#translating-google-docs-to-markdown)?

**Comment by acrall** [comment]
@maneesha I thought I had. I will be looking at this all later this afternoon following a couple of meetings. I'll try to figure out what I did wrong.

**Comment by maneesha** [comment]
> @maneesha I thought I had. I will be looking at this all later this afternoon following a couple of meetings. I'll try to figure out what I did wrong.

No worries - I just recently updated instructions on what to do when using the Google Docs conversion tool, so you may not have seen that yet.

**Comment by acrall** [comment]
@maneesha This is ready for review but still needs the corrections in the tables that we discussed earlier.

**Pull request merged**
